### PR TITLE
Adding documentation for dratseq utility

### PR DESCRIPTION
**Pull request by karanjeets**
Linked to  DRAT Sequential #49

### CODE REVIEW

**Comment by tbpalsulich** [comment]
Any chance you can convert the doc to a text file? You can use Github markdown and the .md extension to get nice formatting.

**Comment by karanjeets** [comment]
Yes. That's a good idea. I have converted this doc to a text file and is now part of Pull Request #49 
I think it's better to close this Pull request as redundant.

**Comment by tbpalsulich** [comment]
+1 all around. :)

**Comment by chrismattmann** [comment]
+1 nice to see you @tpalsulich

**Pull request closed without merging**
