### PR TITLE
Move information over to wiki about how to install and use DRAT.

### PR DESCRIPTION
**Pull request by tbpalsulich**

### CODE REVIEW

**Comment by chrismattmann** [comment]
Hey @tpalsulich i'm wondering on this - it's nice to have a self contained README.md that someone gets when they git clone DRAT. This pushes all that information to the wiki, which is great, but at the same time, makes the README.md less stand alone. That said I'm +0.5 in commiting this patch and may do so, but what are your thoughts on how to handle this?

**Comment by tbpalsulich** [comment]
I agree that having a local copy of the readme is convenient. So, we could also make a note in the (shortened) readme that if you want a local copy of the docs, clone the DRAT wiki with  
`git clone git@github.com:chrismattmann/drat.wiki.git`

That way, we don't have to duplicate documentation between the readme/wiki and users can decide if they want the full set of docs. In my opinion, the readme is too big right now to effectively show all of the information.

What do you think?

**Comment by tbpalsulich** [comment]
Just added a link to the bottom of the readme for how to get a local copy of the DRAT wiki.

**Comment by chrismattmann** [comment]
Sounds great merged it @tpalsulich

**Comment by tbpalsulich** [comment]
Thanks, @chrismattmann!

**Pull request merged**
