### PR TITLE
Updating to meet Apache requirements

### PR DESCRIPTION
**Pull request by wmburke**
https://whimsy.apache.org/site/project/drat

* Added event banner in lower right
* tweaked urls to match expectations
* added "the" to ASF
* Added copyright word instead of symbol

### CODE REVIEW

**Comment by wmburke** [comment]
Just waiting for someone else to check to make sure I didn't do anything stupid. @chrismattmann @ottlinger

**Comment by chrismattmann** [comment]
LGTM!

**Comment by ottlinger** [comment]
Would it make sense to change the footer to 
`(c) 2017-2018` ?

**Comment by wmburke** [comment]
Huh - I honestly don't know how those things are supposed to work. Sorry, I don't have an answer, @ottlinger .

**Pull request merged**
