### PR TITLE
Website first draft

### PR DESCRIPTION
**Pull request by nipurndoshi**
#98 

I hope I created pull request for the correct branch. @buggtb please let me know if something needs to be changed.

### CODE REVIEW

**Comment by ottlinger** [comment]
Please do not checkin .DS_Store-files .... you may want to add a .gitignore file with:
.DS_Store
in it.

**Comment by nipurndoshi** [comment]
Ah! Doing that.

**Comment by nipurndoshi** [comment]
@ottlinger done.

**Comment by wmburke** [comment]
@nipurndoshi I have made some mods to your draft page, including adding hyperlinks and just some minor clean up stuff. I'll be submitting that as a merge request to your repo soon.

@ottlinger The Mission Statement that you put together for your original website: is that original content or does it live elsewhere? I don't want to lose the content when we switch to the new website.

@nipurndoshi (or anyone else with bright ideas):

1. Can we set up an automated way to populate the list of contributors using http://people.apache.org/phonebook.html - and then supplementing that list with gravatars or github avatars or whatever? Currently, it's just all blanks and that clearly won't do. ;)

2. What is the link to publications supposed to be?

3. We should add a link to our mailing list: dev@drat.apache.org - that could go next to the Github link under Resources or elsewhere. If there are no Publications, maybe this section title should change to "How to Contribute" or something similar.

Finally, and this is a total aside, I just learned that html <button>'s are not intended to operate as hyperlinks, so I changed the <button>'s on the page to <a>'s and since they have class="btn", you can't even tell. Thought others might find that useful.

Wayne

**Comment by ottlinger** [comment]
@wmburke Why don't you just tag the current sources as a pre-release, so it's easy to get back and have a look?! I've extracted the abstract from a mail to ASF.

**Comment by wmburke** [comment]
@ottlinger If I'm understanding your question:  I thought that it was good content that would help people to wrap their heads around the value of the tool so I was wondering if it was on the wiki or somewhere else or if it's original content. If it doesn't exist elsewhere, then we could put some time into figuring out where to put it so that it is accessible to new and potential users.

Does that answer the question?

**Comment by ottlinger** [comment]
@wmburke you may use the text for whatever you like if useful.... since I'm a ASF-contributor there's nothing to fear from a legal perspective. Feel free to go ahead :-)

**Comment by buggtb** [comment]
For the phonebook generator stuff, I created a plugin for Jekyll to build our list on OODT that I'm sure could be reworked for static sites: https://github.com/apache/oodt/blob/site-dev/_plugins/pcm_generator.rb

**Comment by wmburke** [comment]
@nipurndoshi If automating the contributor list looks difficult, let's just manually create it for right now and then we can open a new issue to automate it. You can pull the pix for folks from Github - at least for most of them.

@ottlinger Thanks - I've put your Mission Statement text on the GitHub wiki for now - as we flesh out the rest of our docs, we can find a more permanent home for it.

**Comment by wmburke** [comment]
@nipurndoshi Is this realistic for you to pull together? If not, please let us know. If it is, please give us an ETA. Thanks.

**Comment by nipurndoshi** [comment]
@wmburke oh I missed out on your comments until today. I'll make the changes you've suggested and push in a couple of days. I have also merged your fixes.

**Comment by nipurndoshi** [comment]
@wmburke I have taken list of contributors from Github and replaced Publications with Contribute text. Feel free to take a look!

**Comment by chrismattmann** [comment]
it looks fantastic! I am going to merge it!

**Comment by chrismattmann** [comment]
one thing I think we should do is to simply list the PMC members first, then list contributors. I'll update this.

**Comment by wmburke** [comment]
Thanks, @nipurndoshi! Great work! Now we're stylin'...

**Comment by buggtb** [comment]
Yeah that new site is excellent!

**Pull request merged**
