### PR TITLE
Updates for OODT 1.9 to work with Avro communications

### PR DESCRIPTION
**Pull request by IMS94**
This PR includes changes required for OODT 1.9 update.
I think this should not be merged since OODT 1.9 is not released yet and is in SNAPSHOT stage still.

### CODE REVIEW

**Review by chrismattmann — APPROVED** [review]
LGTM

**Comment by chrismattmann** [comment]
I am fine to merge this even with a 1.9-SNAPSHOT dependency. If there aren't any objections in the next 24 hours I will merge...

**Comment by IMS94** [comment]
@chrismattmann I will do one more test run with DRAT and confirm. Then you can merge.

**Comment by chrismattmann** [comment]
@IMS94 are you done testing can I merge?

**Comment by IMS94** [comment]
@chrismattmann Seems like there are some problems. @ahmedifhaam encountered some errors in my version. Have to look at that again

**Comment by chrismattmann** [comment]
got it. Let me know once I can test thanks @IMS94

**Comment by chrismattmann** [comment]
@IMS94 closer to being done?

**Comment by IMS94** [comment]
@chrismattmann No, I have the `workflowInstanceId` being null problem in `StdPgeTaskInstance` for task `MimeTypePartitioner`. Once I fix that in OODT side, we can merge this. Otherwise, @ahmedifhaam will encounter problems when carrying on the GSoC project and DRAT master will be unstable.

**Comment by chrismattmann** [comment]
@IMS94 I think we need to handle the issue you are seeing in OODT - with InstanceId being flowed down - did you fix that?

**Comment by IMS94** [comment]
@chrismattmann I'm in the process of doing that. Will need few more days.

**Comment by chrismattmann** [comment]
💯

**Comment by chrismattmann** [comment]
@IMS94 any progress on getting this finished?

**Comment by IMS94** [comment]
@chrismattmann working on it these days

**Comment by IMS94** [comment]
@chrismattmann Done. Now DRAT can work with avro in OODT. Please check and verify.

**Comment by IMS94** [comment]
Closing this PR as it was discussed to make XML Rpc the default in OODT 1.9 and DRAT for now.

**Pull request closed without merging**
