### PR TITLE
Added --exclude feature to DRAT

### PR DESCRIPTION
**Pull request by karanjeets**
Please refer to the documentation in docs folder

### CODE REVIEW

**Comment by karanjeets** [comment]
Linked to Issue #19

**Comment by chrismattmann** [comment]
this looks great @karanjeets ! Can you update to OODT 0.11 and test it?

**Comment by karanjeets** [comment]
I tried updating to OODT 0.11 in DRAT using maven build but failed. So, I took an update of OODT cas-metadata 0.11 and used its jar to test the functionality. It is working fine.

**Comment by lewismc** [comment]
You can use 0.11-SNAPSHOT as your dependency version. You will need to add
the Apache snapshot repository to the drat Pom.xml.
Oodt publishes nightly snapshot artifacts to the Apache repository.

On Saturday, October 17, 2015, Karanjeet Singh notifications@github.com
wrote:

> I tried updating to OODT 0.11 in DRAT using maven build but failed. So, I
> took an update of OODT cas-metadata 0.11 and used its jar to test the
> functionality. It is working fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/pull/51#issuecomment-148948069.

## 

_Lewis_

**Comment by karanjeets** [comment]
@lewismc 
I tried running that but I am getting below compilation error.

```
Downloaded: http://repository.apache.org/snapshots/org/apache/oodt/pcs-core/0.11-SNAPSHOT/maven-metadata.xml (2 KB at 0.3 KB/sec)
[WARNING] The POM for org.apache.oodt:pcs-core:jar:0.11-20151016.091504-33 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dms-extensions ---
[INFO] Deleting /root/git_workspace/drat/extensions/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dms-extensions ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dms-extensions ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /root/git_workspace/drat/extensions/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/git_workspace/drat/extensions/src/main/java/org/apache/drat/pge/DRATPGETaskInstance.java:[22,33] package org.apache.oodt.cas.crawl does not exist
[ERROR] /root/git_workspace/drat/extensions/src/main/java/org/apache/drat/pge/DRATPGETaskInstance.java:[23,33] package org.apache.oodt.cas.crawl does not exist
[ERROR] /root/git_workspace/drat/extensions/src/main/java/org/apache/drat/pge/DRATPGETaskInstance.java:[30,8] cannot access org.apache.oodt.cas.workflow.structs.WorkflowTaskInstance
  class file for org.apache.oodt.cas.workflow.structs.WorkflowTaskInstance not found
[ERROR] /root/git_workspace/drat/extensions/src/main/java/org/apache/drat/pge/DRATPGETaskInstance.java:[57,36] cannot find symbol
  symbol:   variable this
  location: class org.apache.drat.pge.DRATPGETaskInstance
```

**Comment by chrismattmann** [comment]
@karanjeets it's the version of Java you are using. I believe OODT 0.11 was published with Java7. Please make sure your Java version is 7 or greater.

**Comment by karanjeets** [comment]
@chrismattmann : Finally, I got it working. Sorry to bother you. I deleted `.m2` directory and then did a clean install.
However, now with OODT 0.11, I am facing another issue while running crawler. Do I need to add any extra dependencies in DRAT pom ?

```
Exception in thread "main" java.lang.NoClassDefFoundError: com_atlassian_clover/TestNameSniffer
        at org.apache.oodt.cas.crawl.CrawlerLauncher.<clinit>(CrawlerLauncher.java:32)
Caused by: java.lang.ClassNotFoundException: com_atlassian_clover.TestNameSniffer
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more
```

**Comment by chrismattmann** [comment]
Please file an OODT bug and tag tom barber

**Comment by chrismattmann** [comment]
@buggtb you broke OODT build

**Comment by buggtb** [comment]
That would be the last error I would expect I'll have a look shortly

**Comment by karanjeets** [comment]
Thanks @buggtb 
I have raised a JIRA ticket as well [OODT-893](https://issues.apache.org/jira/browse/OODT-893) to keep a track of this.

**Comment by buggtb** [comment]
Thanks.  It's odd because those clover instrumented builds aren't supposed
to be installed in a public maven repository so either it's a stale build
our I've left something switched on by mistake somewhere.

Tom

**Comment by buggtb** [comment]
Ack, balls, I left an install in the oodt-coverage build that was publishing the snapshot.

Sorry @karanjeets @chrismattmann complete oversight on my part, I can't see the jira as the ASF jira is down, so consider this a response until I can update it.

I've removed the install command from the maven build and I'm waiting on Jenkins to rebuild an non instrumented version: https://builds.apache.org/job/oodt-trunk/

@karanjeets when build 2038 is complete can you remove the oodt jars from your ~/.m2 repository and try again and let me know how you get on.

Apologies again!

Tom

**Comment by karanjeets** [comment]
@buggtb  Thanks for correcting this. The crawler is running fine now. :)

@chrismattmann Tested with OODT 0.11-SNAPHOT. The --exclude functionality is working as expected. :)

**Comment by chrismattmann** [comment]
Great work!

**Comment by karanjeets** [comment]
@chrismattmann  

Thanks for merging this. I think we need to change the pom.xml as well to OODT 0.11-SNAPSHOT or better way would be to comment the RegEx pre-condition in crawler policy until DRAT is not moved to OODT 0.11. 

Currently it is breaking saying Cannot find class [org.apache.oodt.cas.metadata.preconditions.RegExExcludeComparator] as it is not present in OODT 0.10.

**Comment by lewismc** [comment]
Please see the new snapshot branch for the trivial upgrade. i think it is a good idea for DRAT to run off of SNAPSHOT. We are about to release DRAT I think so it would be nice to iron this out before we do.

**Pull request merged**
