### PR TITLE
Fix for incorrect project popping after pagination or search on projects

### PR DESCRIPTION
**Pull request by ahmedifhaam**
-was passing the index as the parameter and now passing the element it
self

### CODE REVIEW

**Comment by ahmedifhaam** [comment]
@chrismattmann can you check this once

**Comment by chrismattmann** [comment]
yes sorry @ahmedifhaam i will work on this tonight! will get back to you right away. Will you have time to work on the next updates?

**Comment by ahmedifhaam** [comment]
@chrismattmann Yes chris im working on them will get them soon

**Comment by chrismattmann** [comment]
thanks @ahmedifhaam

**Pull request merged**
