### PR TITLE
DRAT Sequential

### PR DESCRIPTION
**Pull request by karanjeets**
Adding dratseq to run DRAT sequentially on multiple repositories

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @karanjeets I think this probably justifies an update to the documentation as well? Nice utilility script I like it.

**Comment by karanjeets** [comment]
Thanks @lewismc 
Sure, I will add documentation to the project's docs folder soon.

**Comment by karanjeets** [comment]
@lewismc 
Submitted a pull request (#50) for the documentation on DRAT Sequential utility. I hope it will be useful.

**Comment by lewismc** [comment]
Brilliant. We love documentation :)
Will merge unless someone else beats me to it.
Nice job.

On Thursday, September 24, 2015, Karanjeet Singh notifications@github.com
wrote:

> @lewismc https://github.com/lewismc
> Submitted a pull request (#50
> https://github.com/chrismattmann/drat/pull/50) for the documentation on
> DRAT Sequential utility. I hope it will be useful.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chrismattmann/drat/pull/49#issuecomment-143110297.

## 

_Lewis_

**Comment by chrismattmann** [comment]
looks great +1 to merge @karanjeets @lewismc

**Comment by lewismc** [comment]
Hi @chrismattmann 

```
lmcgibbn@LMC-032857 /usr/local/drat(master) $ git push origin master
Username for 'https://github.com': lewismc
Password for 'https://lewismc@github.com':
remote: Permission to chrismattmann/drat.git denied to lewismc.
fatal: unable to access 'https://github.com/chrismattmann/drat.git/': The requested URL returned error: 403
```

**Comment by chrismattmann** [comment]
One sec will fix

**Comment by chrismattmann** [comment]
@lewismc you can try and commit it now

**Comment by lewismc** [comment]
#bewm

**Comment by chrismattmann** [comment]
ACK'ed

**Pull request merged**
